Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

config.vm.provision "shell", path: "./install_all.sh"

config.vm.provider "virtualbox" do |vb|
   vb.memory = "8192"
 end


# Uncomment to share workshop dir synced with VM
# May require administrative privilegdes on host

# config.vm.network "private_network", ip: "192.168.33.99" 
# config.vm.synced_folder "../", "/workshop", nfs: true
# nfs driver requires you enter your host admin password on vagrant up


config.vm.post_up_message = <<-HEREDOC
  Debian VM with Minikube, Docker and other tools installed
  See scripts in /vagrant to install Falco daemonset
HEREDOC



end
