Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end
  config.vm.provision "shell", path: "./setup_ssh.sh"

  # config.vm.network "private_network", ip: "192.168.33.99" 
  # config.vm.synced_folder "../", "/workshop", nfs: true

end
